#!/usr/bin/env bash
# Build a markdown digest from upstream commit + release + PR data
set -euo pipefail

COMMITS_FILE="${1:-/tmp/raw_commits.json}"
RELEASES_FILE="${2:-/tmp/releases.json}"
PRS_FILE="${3:-/tmp/our_prs.json}"

# High-signal file patterns — flag commits touching these
WATCH_PATTERNS=(
  "agent-scope"
  "schema.ts"
  "types.agents"
  "compaction"
  "memory"
  "plugin-sdk"
  "breaking"
)

echo "## 📡 Upstream Digest — $(date -u '+%Y-%m-%d %H:%M UTC')"
echo ""

# --- Releases ---
RELEASE_COUNT=$(cat "$RELEASES_FILE" | jq -s 'flatten | length' 2>/dev/null || echo "0")
if [ "$RELEASE_COUNT" -gt 0 ]; then
  echo "### 🚀 New Releases"
  echo ""
  cat "$RELEASES_FILE" | jq -rs 'flatten | .[] | "- **\(.tag)** — \(.name) (\(.date[0:10]))\n  \(.body | split("\n")[0])"'
  echo ""
fi

# --- Commits ---
COMMIT_COUNT=$(cat "$COMMITS_FILE" | jq -s 'flatten | length' 2>/dev/null || echo "0")
if [ "$COMMIT_COUNT" -gt 0 ]; then
  echo "### 📝 Commits to main ($COMMIT_COUNT new)"
  echo ""
  
  # Categorize commits
  HAS_ALERT=false
  
  cat "$COMMITS_FILE" | jq -rs 'flatten | .[] | "\(.sha) \(.message)"' | while IFS= read -r line; do
    SHA=$(echo "$line" | cut -d' ' -f1)
    MSG=$(echo "$line" | cut -d' ' -f2-)
    
    # Check if commit touches watched files
    IS_ALERT=false
    for pattern in "${WATCH_PATTERNS[@]}"; do
      if echo "$MSG" | grep -qi "$pattern"; then
        IS_ALERT=true
        break
      fi
    done
    
    if [ "$IS_ALERT" = true ]; then
      echo "- ⚠️ \`$SHA\` $MSG"
    else
      echo "- \`$SHA\` $MSG"
    fi
  done
  echo ""
  
  # Summary of file areas touched
  echo "<details><summary>Files touched</summary>"
  echo ""
  cat "$COMMITS_FILE" | jq -rs '[flatten | .[].files[]?] | group_by(split("/")[0]) | .[] | "- **\(.[0] | split("/")[0])/** (\(length) files)"' 2>/dev/null || echo "- *(file details not available)*"
  echo ""
  echo "</details>"
  echo ""
fi

if [ "$COMMIT_COUNT" = "0" ] && [ "$RELEASE_COUNT" = "0" ]; then
  echo "*No upstream changes since last check.*"
  echo ""
fi

# --- Our PRs ---
PR_COUNT=$(cat "$PRS_FILE" | jq -s 'flatten | length' 2>/dev/null || echo "0")
if [ "$PR_COUNT" -gt 0 ]; then
  echo "### 🔀 Our Open PRs"
  echo ""
  cat "$PRS_FILE" | jq -rs 'flatten | .[] | "- **#\(.number)** \(.title) — \(if .draft then "📝 Draft" else "🟢 Open" end) | reviews: \(.review_comments) | updated: \(.updated_at[0:10])"'
  echo ""
fi

# --- Footer ---
echo "---"
echo "*Generated by [openclaw-mods](https://github.com/curtismercier/openclaw-mods) upstream monitor*"
